# Generated by Django 5.0 on 2023-12-05 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sual_metni', models.CharField(max_length=200)),
                ('qeydiyyat_tarixi', models.DateTimeField(verbose_name='gorunen tarix')),
            ],
        ),
        migrations.CreateModel(
            name='Secim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secim_metni', models.CharField(max_length=200)),
                ('sesler', models.IntegerField(default=0)),
                ('sual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sesverme.sual')),
            ],
        ),
    ]
